### ISSUE TITLE
No edits in the Airflow Cloud Formation script reflects in the 

### ISSUE THREAD

**Issue by saveriogzz** [san089/Data_Engineering_Projects#6]
Hey!
I'm trying to replicate some of the steps you followed to create an Airflow server on CloudFormation.. but even editing the section "UserData" of the EC2 instance, my changes are not reflected on the machine, i.e. I don't have apache airflow installed, python is still the 2.7 version, ecc..
Do you have any idea how i can solve this?

Thanks!
Saverio

**Comment by san089** [comment]
Hi Saverio,

I don't have much idea about it as I did it a long time ago and also did
not face any issue with it. However, there are certain things you need to
check. About the python version, I believe python3 would have already been
installed but the env variable need to be set for it. Do the below:

1.) run command 'python' -> check python version and exit out of python
shell. Then run command 'python3' and see if the version is different. If
it's different it simply means that python3 is installed on the machine but
the path variable is not pointing to python3. You can check follow the
thread below:
https://stackoverflow.com/questions/5846167/how-to-change-default-python-version

2.) For airflow installation, not sure but I think you need to set the path
variable for this as well. Check if this works for you.:
https://limitlessdatascience.wordpress.com/2019/10/01/apache-airflow-installation-steps/

Finally, I do believe that setup should work but in case it did not, I
recently came across docker image for airflow setup which is pretty easy to
setup. Check this:
https://towardsdatascience.com/apache-airflow-and-postgresql-with-docker-and-docker-compose-5651766dfa96


Thanks
Sanchit Kumar

**Comment by saveriogzz** [comment]
Thank you San! :)
